LOOK AWAY. I AM HIDEOUS. 

This is in progress so keep your creeper eyes away from it. 

A lot has changed. Do not look at this read me. 

* Ideas for orgmode clones

I want to be able to clone an orgmode heading so that it can appear in different places in an outline. When I edit one of these headings, I want the changes to sync to all the other clones. It is a feature of Leo Editor, /see/ https://leoeditor.com/tutorial-pim.html, which I wish I could use but it’s not in Emacs so it is dead to me.

* Why clones?
Let’s say you have an outline with two headings:

#+begin_src org
* Animals
* Animals you can eat
#+end_src

And you want to add a heading for chickens. Oh shit. Where does it go? It goes under both headings. Until now, orgmode could not do that. Now, it can /kind of/ do it. 

#+begin_src org
* Animals
** Chickens
* Animals you can eat
** Chickens
#+end_src

Watch: [insert demo.]
* Terminology
I use the following words to describe the following things:

"Node" means an entry in an org outline. 

"Headline" means the headline text of the entry, but does not include the headline's todo state or tags

"Body" means everything after the headline, planning line, and property drawers until the next node.

* Installation 
** Dependencies
None except org and org-id
* Usage
* Task list
- [ ] What the fuck is up with the org-id problem!? [I don’t know yet.]
- [X] Write functions to jump to next clone [just need to figure out the header line problem, or use a different way of handling it.]
- [X] Clean up overlay and text properties
- [X] When the point enters a sensor field, add a space to be able to add to the end of the field [solution was a disaster]
- [X] Remove =org-ql=
- [X] Remove =org-ml=
- [X] Remove =ov=
- [X] Fix putting all clone effects on startup so it is properly recursive [no recursion; done though enabling mode]
- [X] Fix =org-clones--goto-body-start= to skip closing note logs [also harder than I thought]
- [X] Figure out how to handle having multiple buffers open
- [X] Get rid of goto-headline-start... and similar functions (only need get- functions) [abandoned]
- [X] Fix org-clones--remove-text-properties to remove only the text props at issue
- [X] When removing cursor-sensor text properties, only remove our function from the list and preserve any other functions
- [X] Fix removing overlays 




* Other transclusion efforts
Here are some other transclusion efforts or discussions of such efforts:

https://github.com/alphapapa/transclusion-in-emacs

https://github.com/justintaft/emacs-transclusion/blob/master/emacs-transclusion.el

https://github.com/gregdetre/emacs-freex

All very interesting, but I want one thing: headings that can appear anywhere that will be synced when edited. That’s it. 

